### ISSUE TITLE
Pet not showing happiness level

### ISSUE THREAD

**Issue by xapher19** [AzeriteTeam/AzeriteUI_Classic#1]
The little icon that shows pet happiness doesn't show up.

**Comment by goldpaw** [comment]
Will get to this eventually, not having a level 10 hunter with a pet to personally develop this on yet.

**Comment by goldpaw** [comment]
There is a weakaura for pet happeniss that might help until then: 
https://wago.io/uVcrRuwDW/1

**Comment by goldpaw** [comment]
Added in 1.0.27-RC, or attempted to!
