### ISSUE TITLE
Can the classic version be suitable for displaying squad member information?

### ISSUE THREAD

**Issue by yz0932** [AzeriteTeam/AzeriteUI_Classic#10]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by goldpaw** [comment]
No idea what this is about, just an empty template and sort a question in the title here. 

If the question is, will there be party frames? Then yes, eventually. 

If the question/problem is that you can't see your party members currently at all, then hit the Esc key, go to "Interface Options", then to "Raid Profiles", and click the box to "Use Raid-Style Party Frames". Then you'll get the blizzard compact frames for parties too. 

![Screenshot from 2019-09-11 14-12-48](https://user-images.githubusercontent.com/6476535/64696306-60796300-d49e-11e9-9685-667abb97291c.png)

**Comment by yz0932** [comment]
First of all, thank you very much for your answer. Sorry, I am using this forum for the first time and I am not very familiar with it. Then I will continue to test in the game.
Finally, I am very grateful for your development, so I can use such a great UI design.
Thank you
