### ISSUE TITLE
It's about Chat Frame. I don't know it's a bug or what

### ISSUE THREAD

**Issue by nousernameeee** [AzeriteTeam/AzeriteUI_Classic#12]
Sorry about my terrible English.
I wanna create a new chat frame, but it didn't show any words, even I pick every single chat channel.
Only show words on the Main Chat Frame.

**Comment by goldpaw** [comment]
Yeah, it's a bug and I'm working on figuring it out. This has been reported already, though, in #8

**Comment by goldpaw** [comment]
Fixed in 1.0.46-RC.

**Comment by nousernameeee** [comment]
thanks!
