### ISSUE TITLE
Extra buttons repeating

### ISSUE THREAD

**Issue by Elthalas** [AzeriteTeam/AzeriteUI_Classic#13]
Hi! 

I've found that when I select the option of adding either 11 or 17 extra buttons, the added buttons are a mirror of the ones that are already present. So I really cant use them, because if I add a spell in one place, it immediatly changes in the other.
It's easy to see in the attached image. I started with a clean bar, and I added spells only in the first 12 buttons; the other ones appearead by themselves, reflecting the first ones. 

![WoWScrnShot_091819_000514](https://user-images.githubusercontent.com/55465627/65083176-1d405800-d9a8-11e9-849f-a92ccdd3b81f.jpg)

Thank you for your great job!

**Comment by goldpaw** [comment]
Bet you had accidentally switched the page of your main bar. Shift + mousewheel ftw! ;)
