### ISSUE TITLE
Why can't I display the team frame?

### ISSUE THREAD

**Issue by fun4crazy** [AzeriteTeam/AzeriteUI_Classic#14]
Is the party frame hidden?

**Comment by goldpaw** [comment]
Yes, haven't added our own group frames yet. Set the Blizzard raid frames to be used for parties as well, in the interface options. Then they'll show up: 

![Screenshot from 2019-09-18 11-48-26](https://user-images.githubusercontent.com/6476535/65137854-56111900-da0a-11e9-8a00-0854ebe426f3.png)

**Comment by fun4crazy** [comment]
OK , thank you~
 
------------------
https://sz-ctfs.ftn.qq.com/ftn_handler/3c681ffebd4df3834886d810b2f0259bee2db9aa8df38caf79b6c4e083265de3/?fname=*.jpg&pictype=scaled&size=64*64



 




------------------ 原始邮件 ------------------
发件人: "Lars Norberg"<notifications@github.com>; 
发送时间: 2019年9月18日(星期三) 下午5:49
收件人: "AzeriteTeam/AzeriteUI_Classic"<AzeriteUI_Classic@noreply.github.com>; 
抄送: "Mr.31"<1115431@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [AzeriteTeam/AzeriteUI_Classic] Why can't I display the teamframe? (#14)




Yes, haven't added our own group frames yet. Set the Blizzard raid frames to be used for parties as well, in the interface options. Then they'll show up:
