### ISSUE TITLE
AzeriteUI does not show player profiles

### ISSUE THREAD

**Issue by Bashadash** [AzeriteTeam/AzeriteUI_Classic#2]
It does not show when you have people in your party.
![Capture](https://user-images.githubusercontent.com/54693394/63986302-311f2b00-ca88-11e9-8b76-876a948d6c55.PNG)

**Comment by goldpaw** [comment]
Yes it does, but you have to enable the checkbox in the upper-right corner of the raid profile settings tab in the interface menu, to allow party to be shown using the raid frames. Blizzard setting.
