### ISSUE TITLE
Tooltips

### ISSUE THREAD

**Issue by yozoh0755** [AzeriteTeam/AzeriteUI_Classic#20]
### Make sure you can check all these boxes  
I have the latest addon version available from CurseForge/Twitch.

### Does this happen with NO other addons enabled?  

Yes

### What classes does it happen on?  

Any classes 

### Any logs, error output, etc?  
No

### Steps to reproduce  
1. load AzeriteUI,Into the game don’t move mouse and open backpack move mouse check the items tootips ,the fonts of tooltips is normal size.
2. Move the mouse to any target ,the tooltips fonts size turn to small.
3. After that , back to backpack or any other place the tooltips font size alway be small.
Except reload UI.

### Expected behaviour  
Normal font size tooltips.

### Actual behaviour  
Normal turn to small font size.

**Comment by yozoh0755** [comment]
Thanks

**Comment by goldpaw** [comment]
Or, it was a bug. Bag tooltips weren't scaled to match the rest, only after having seen a unit tooltip first. Not intended, and fixed in 1.0.63-RC! :)

**Comment by yozoh0755** [comment]
Thanks for update！And I find a problem in new version. When loot items or open a box or chest the tooltips prices sometime showing wrong, but the prices is exactly the real prices double. Any other situation is working good.

**Comment by goldpaw** [comment]
There was a bug where tooltips would always show the price of a full stack and not the actual amount that was in it in 1.0.62-RC, which I fixed in 1.0.63-RC. Make sure it's not that you're experiencing. 

And please keep it to one problem per issue report. This one was about wrongly scaled tooltips, which is fixed and the issue closed!

**Comment by yozoh0755** [comment]
Get it
