### ISSUE TITLE
Partyframe Buffs from player

### ISSUE THREAD

**Issue by dinotheextinct** [AzeriteTeam/AzeriteUI_Classic#21]
**Is your feature request related to a problem? Please describe.**
Not beeing able to see my own buffs/healing over time effects on party frames is a grave problem as a druid healer.

**Describe the solution you'd like**
I think it would be nice to have like 3-4 buffs visible below the party frame. Or make it like really shiny with showing only direct healing effects like druid hots, priest shields directly on the healthglobe in some eyecandy way, which still is very distinct. Best would be to also track remaining time.

**Describe alternatives you've considered**
Or just simply show bufficons below the party frames but only buffs your class can provide.

**Comment by goldpaw** [comment]
I'm working on this. Need to add some fairly large databases and systems to figure out things like aura durations and similar, and when that's in place aura filters for both party frames and nameplates will get some HUGE upgrades! :) 

Leaving this open until I have more news to share about it.

**Comment by goldpaw** [comment]
Should be HoTs on party frames, and have been for a while. I just forgot to update this issue when it was added.
