### ISSUE TITLE
Targetframe castbar

### ISSUE THREAD

**Issue by dinotheextinct** [AzeriteTeam/AzeriteUI_Classic#22]
**Is your feature request related to a problem? Please describe.**
Beeing able to see in a very clear way what your target is casting is mandatory for PvE and PvP alike.

**Describe the solution you'd like**
Right now the visibility of what beeing cast is very tuned down. So I would prefer a more striking appearance of the castbar. Maybe with an red or purplish glow of the castbar itself so its hard to miss it.

**Describe alternatives you've considered**
Maybe just change the color of the "cast bar" thing in side the targt frame, white/transparent is not visibile enough.

**Comment by goldpaw** [comment]
Nameplates have castbars too. They are right above the enemies heads, are very clear and differently colored from the health bars. The target frame castbar is just meant as an addition to this, not a replacement. 

If the goal is to closely track enemy casts, changing the target frame castbar is not the answer. Enable enemy nameplates. That'll do it.
