### ISSUE TITLE
Mana bars for target and party frames

### ISSUE THREAD

**Issue by AntonioDeCasper** [AzeriteTeam/AzeriteUI_Classic#24]
In classic WoW is very helpfully to see enemy and party's mana pool. Even if you dont reach 60 lvl. Please add this enchancement :)

**Comment by goldpaw** [comment]
Coming!

**Comment by AntonioDeCasper** [comment]
Nice!! Hope this will coming soon, miss this feature very much :)

**Comment by NNaidoo** [comment]
This is seriously required as tank to manage group. Please get this done asap!!

**Comment by goldpaw** [comment]
Target frame has had mana for quite some time. The party and raid frames shows a warning when people have low mana, in the form of the text "oom". White when they are below 30% (I think), red when they are down below 10%. I'm a tank. This combined with mana in the unitframe tooltips works well. Closing this.
