### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by JSZMonkey** [AzeriteTeam/AzeriteUI_Classic#26]
if mouse move on the "Atlas Loot Classic" items 

Message: ...ns\AzeriteUI_Classic\front-end\blizzard\tooltips.lua:361: attempt to perform arithmetic on a table value
Time: Sat Oct 26 01:08:45 2019
Count: 7
Stack: ...ns\AzeriteUI_Classic\front-end\blizzard\tooltips.lua:361: attempt to perform arithmetic on a table value
...ns\AzeriteUI_Classic\front-end\blizzard\tooltips.lua:361: in function <...ns\AzeriteUI_Classic\front-end\blizzard\tooltips.lua:342>
[C]: ?
[C]: ?
[C]: ?
[C]: in function `SetCompareItem'
Interface\FrameXML\GameTooltip.lua:716: in function `GameTooltip_ShowCompareItem'
Interface\FrameXML\GameTooltip.lua:545: in function <Interface\FrameXML\GameTooltip.lua:543>
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: in function `SetHyperlink'
...terface\AddOns\AtlasLootClassic\Button\Item_type.lua:210: in function `OnEnter'
Interface\AddOns\AtlasLootClassic\Button\Button.lua:111: in function <Interface\AddOns\AtlasLootClassic\Button\Button.lua:104>

Locals: tooltip = ShoppingTooltip2 {
 0 = <userdata>
 SetText = <function> defined =[C]:-1
 AddLine = <function> defined =[C]:-1
 GetBackdropColor = <function> defined @Interface\AddOns\AzeriteUI_Classic\back-end\libraries\tooltip.lua:2472
 BottomOverlay = <unnamed> {
 }
 SetFrameStrata = <function> defined =[C]:-1
 updateTooltip = 0.200000
 SetBackdrop = <function> defined @Interface\AddOns\AzeriteUI_Classic\back-end\libraries\tooltip.lua:2470
 TopOverlay = <unnamed> {
 }
 GetBackdropBorderColor = <function> defined @Interface\AddOns\AzeriteUI_Classic\back-end\libraries\tooltip.lua:2473
 GetBackdrop = <function> defined @Interface\AddOns\AzeriteUI_Classic\back-end\libraries\tooltip.lua:2471
 needsReset = true
 MoneyCount = <table> {
 }
 SetFrameLevel = <function> defined =[C]:-1
 AddDoubleLine = <function> defined =[C]:-1
 SetParent = <function> defined =[C]:-1
}
frame = AtlasLoot_Button_3 {
 0 = <userdata>
 SetContentTable = <function> defined @Interface\AddOns\AtlasLootClassic\Button\Button.lua:523
 RawName = "鳄齿利斧"
 GetTypeFunctions = <function> defined @Interface\AddOns\AtlasLootClassic\Button\Button.lua:697
 ItemID = 17730
 formatTab = <table> {
 }
 phaseIndicator = AtlasLoot_Button_3_phaseIndicator {
 }
 SetPreSet = <function> defined @Interface\AddOns\AtlasLootClassic\Button\Button.lua:513
 highlightBg = AtlasLoot_Button_3_highlightBg {
 }
 secButton = AtlasLoot_Button_3_secButton {
 }
 favourite = AtlasLoot_Button_3_favourite {
 }
 SetType = <function> defined @Interface\AddOns\AtlasLootClassic\Button\Button.lua:644
 factionIcon = AtlasLoot_Button_3_factionIcon {
 }
 Clear = <function> defined @Interface\AddOns\AtlasLootClassic\Button\Button.lua:460
 Droprate = 24.930000
 SetDifficultyID = <function> defined @Interface\AddOns\AtlasLootClassic\Button\Button.lua:689
 extra = AtlasLoot_Button_3_extra {
 }
 __atlaslootinfo = <table> {
 }
 GetSecTypeFunctions = <function> defined @Interface\AddOns\AtlasLootClassic\Button\Button.lua:701
 AddEnhancedDescription = <function> defined @Interface\AddOns\AtlasLootClassic\Button\Button.lua:824
 completed = AtlasLoot_Button_3_completed {
 }
 SetNpcID = <function> defined @Interface\AddOns\AtlasLootClassic\Button\Button.lua:693
 count = AtlasLoot_Button_3_count {
 }
 overlay = AtlasLoot_Button_3_overlay {
 }
 SetExtraType = <function> defined @Interface\AddOns\AtlasLootClassic\Button\Button.lua:673
 SetSecType = <function> defined @Interface\AddOns\AtlasLootClassic\Button\Button.lua:660
 name = AtlasLoot_Button_3_name {
 }
 icon = AtlasLoot_Button_3_icon {
 }
}
name = "AtlasLoot_Button_3"
_ = "精灵典礼之刃"
link = "[精灵典礼之刃]"
itemName = "精灵典礼之刃"
itemLink = "[精灵典礼之刃]"
itemRarity = 2
itemLevel = 45
itemMinLevel = 0
itemType = "武器"
itemSubType = "匕首"
itemStackCount = 1
itemEquipLoc = "INVTYPE_WEAPON"
itemIcon = 135311
itemSellPrice = 15775
itemClassID = 2
itemSubClassID = 15
bindType = 1
expacID = 254
itemSetID = nil
isCraftingReagent = false
itemCount = AtlasLoot_Button_3_count {
 0 = <userdata>
}
label = "卖价:"
(*temporary) = <function> defined @Interface\AddOns\AzeriteUI_C

**Comment by JSZMonkey** [comment]
The plugin conflicts with “zTip” after updating to version 1.0.63-RC

**Comment by goldpaw** [comment]
fixed in 1.0.64-RC.
