### ISSUE TITLE
Dispellable Icons on Party and Raid Frames

### ISSUE THREAD

**Issue by YuelLi** [AzeriteTeam/AzeriteUI_Classic#29]
Really need that feature for wow classic raid lol

**Comment by goldpaw** [comment]
Well it's there. As a druid I get curse icons on the party frames, even when I'm the tank or a damage dealer. If it's not working for you, this is a bug! 

What class and spec are you, and what dispellable debuffs aren't showing for you?

**Comment by YuelLi** [comment]
> Well it's there. As a druid I get curse icons on the party frames, even when I'm the tank or a damage dealer. If it's not working for you, this is a bug!
> 
> What class and spec are you, and what dispellable debuffs aren't showing for you?

Thanks for the response. Mage here, So are the curses lol. I don't have some curses from Stratholme

**Comment by goldpaw** [comment]
Well are you positive they actually are curses? Some debuffs are called "Curse of blablabla" while they're in fact magic.

**Comment by goldpaw** [comment]
If the border color of the debuff on the target/player frame when you target the person with it is anything other than purple, than it's not a curse.
