### ISSUE TITLE
Latest Version doesn't load

### ISSUE THREAD

**Issue by eTzmNcbkrng** [AzeriteTeam/AzeriteUI_Classic#3]
## The problem  
Latest version does not load at all, several errors received.

### Make sure you can check all these boxes  
- [Done] I have the latest addon version available from CurseForge/Twitch.
- [Done] I restarted the entire game after updating the addon, not just relogged or reloaded. 

### Does this happen with NO other addons enabled?  

- [Yes] Yes

### What classes does it happen on?  

- [Only one tested] Druid 
- [ ] Hunter 
- [ ] Mage 
- [ ] Paladin 
- [ ] Priest 
- [ ] Rogue 
- [ ] Shaman 
- [ ] Warlock 
- [ ] Warrior 

### Any logs, error output, etc?  
First Error: https://pst.klgrth.io/paste/9z47qgzuxf7hz9224opp495s
Second Error: https://pst.klgrth.io/paste/ypv3nvtrfnotnewrx9fqzdvg

### Steps to reproduce  
Login

### Expected behaviour  
Should have AzeriteUI

### Actual behaviour  
Displays only Default/Blizzard UI elements, and a few lua errors.

**Comment by goldpaw** [comment]
Only happens to those that have some other full UI like TukUI, ElvUI installed too. 
Fixed in 1.0.29-RC.
