### ISSUE TITLE
Quest problem with Azerite (Questie)

### ISSUE THREAD

**Issue by Khaylel** [AzeriteTeam/AzeriteUI_Classic#30]
Hello, I have a problem. I have the addon Questie and with Azerite i'm unable to see quest objectives on the nameplates. How can I resolve? Ty in advace...

**Comment by goldpaw** [comment]
It's not an incompatibility per say, as our nameplates are not the blizzard nameplates. I did for a while consider building in support for this, but eventually decided against it. It's always possible to use another nameplate addon that supports it, but our will remain as simplistic as possible.
