### ISSUE TITLE
Maybe petframe？

### ISSUE THREAD

**Issue by nousernameeee** [AzeriteTeam/AzeriteUI_Classic#31]
Hello, me again  :)
Just wondering is there any chance to add petframe to the partyframe and raidframe. Cause for a healer, it really pain in the ass to fine the pet during the battle.
And I find there is one version, that partyframe has 3buffs show below the partyframe. Why canceled it.
Sorry for my terrible english. XD

**Comment by goldpaw** [comment]
This has been in the addon for a few weeks no, just forgot to close this request. :)
