### ISSUE TITLE
Error when opening default Raid profiles option

### ISSUE THREAD

**Issue by dinotheextinct** [AzeriteTeam/AzeriteUI_Classic#32]
> Message: ...rd_CUFProfiles\Blizzard_CompactUnitFrameProfiles.lua:455: Usage: GetRaidProfileOption("profile", "optionName")
Time: Sun Nov 17 11:56:40 2019
Count: 2
Stack: ...rd_CUFProfiles\Blizzard_CompactUnitFrameProfiles.lua:455: Usage: GetRaidProfileOption("profile", "optionName")
[C]: in function `GetRaidProfileOption'
...rd_CUFProfiles\Blizzard_CompactUnitFrameProfiles.lua:455: in function `initFunction'
Interface\FrameXML\UIDropDownMenu.lua:79: in function `UIDropDownMenu_Initialize'
...rd_CUFProfiles\Blizzard_CompactUnitFrameProfiles.lua:443: in function `CompactUnitFrameProfilesDropdown_OnShow'
[string "*:OnShow"]:1: in function <[string "*:OnShow"]:1>
[C]: in function `Show'
Interface\FrameXML\UIParent.lua:2078: in function `SetUIPanel'
Interface\FrameXML\UIParent.lua:1884: in function `ShowUIPanel'
Interface\FrameXML\UIParent.lua:1784: in function <Interface\FrameXML\UIParent.lua:1780>
[C]: in function `SetAttribute'
Interface\FrameXML\UIParent.lua:2526: in function `ShowUIPanel'
Interface\FrameXML\UIParent.lua:2547: in function `ShowOptionsPanel'
[string "*:OnClick"]:2: in function <[string "*:OnClick"]:1>

Locals: (*temporary) = nil
(*temporary) = "healthText"

**Comment by dinotheextinct** [comment]
Still cant open defautl raid frames regardless of azerite party/raid frame settings.

**Comment by goldpaw** [comment]
This is more often than not a blizzard problem with how they save profiles, so a common solution is to choose a valid profile when no addons are enabled, then re-enable addons, and the dropdown should work fine. I have seen this since raid profiles came, and have yet to figure out the actual cause nor find a solution.
