### ISSUE TITLE
Erreur LUA since i've reached the 60 level

### ISSUE THREAD

**Issue by FidjiStorm** [AzeriteTeam/AzeriteUI_Classic#33]
## The problem  
Hi,  Since i've reached the 60 level with my priest i receive a LUA erreur !
I tried to remove all the other addons that i had installed previously and have installed the last version for the classic version but without success !   When i'm using another character like my mage i don't have this error message !  This character don't have already reached the 60 level,....

### Make sure you can check all these boxes  
- [X] I have the latest addon version available from CurseForge/Twitch.
- [X] I restarted the entire game after updating the addon, not just relogged or reloaded. 

### Does this happen with NO other addons enabled?  

- [X] Yes
- [ ] No

### What classes does it happen on?  

- [ ] Druid 
- [ ] Hunter 
- [ ] Mage 
- [ ] Paladin 
- [X] Priest 
- [ ] Rogue 
- [ ] Shaman 
- [ ] Warlock 
- [ ] Warrior 

### Any logs, error output, etc?  

https://pastebin.com/5Ht26BgC

### Steps to reproduce  

I don't have modified my way to use Azeriteui the only thing i've done is to reached the 60 level.

### Actual behaviour  

If i use the reload button on the error message window, then i return back on the classic display of wow classic to have Azeriteui on the screen i have to reload Wow classic completely but i'll have the error message 5 seconds later.

I hope that you'll have a idea how to solve my problem.

Thanks a lot and have a great day

**Comment by goldpaw** [comment]
No idea why it's bugging out, but what faction reputation are you currently tracking and what reputation level (honored, friendly, revered etc) are you currently at? 

Because it's something there that's bugging out in some way I'm not sure about yet.

**Comment by goldpaw** [comment]
Nvm my last question. There's a bug in the French translation of the UI, you're probably on a French realm. It'll be fixed in the next update! :)

**Comment by goldpaw** [comment]
Fixed in 1.0.87-RC, which should be available on Curse/Twitch anything from some minutes to some hours from now.

**Comment by FidjiStorm** [comment]
You right Goldpaw i was on a french server !   And now indeed with your new update everything seems to work perfectly !

Thanks a lot
