### ISSUE TITLE
can't switch the pet stance by using the keybind since 1.95rc

### ISSUE THREAD

**Issue by leccco** [AzeriteTeam/AzeriteUI_Classic#34]
## The problem  
can't switch the pet stance by using the key-bind since 1.95rc but can do it by left-clicking on the pet bar,so what i did wrong or it's just a bug.

### Make sure you can check all these boxes  
- [*] I have the latest addon version available from CurseForge/Twitch.
- [ ] I restarted the entire game after updating the addon, not just relogged or reloaded. 

### Does this happen with NO other addons enabled?  

- [*] Yes
- [ ] No

### What classes does it happen on?  

- [ ] Druid 
- [*] Hunter 
- [ ] Mage 
- [ ] Paladin 
- [ ] Priest 
- [ ] Rogue 
- [ ] Shaman 
- [ ] Warlock 
- [ ] Warrior 

### Any logs, error output, etc?  
no

### Expected behaviour  
just tell me what to do or fix it .

### Actual behaviour  
really apreciate your guys' work,it make the game even greater!

**Comment by goldpaw** [comment]
Forgot to close this issue, but this was a problem with the pet button template that was fixed some time after this issue.
