### ISSUE TITLE
Azerite Crystal UI Element

### ISSUE THREAD

**Issue by srtzero** [AzeriteTeam/AzeriteUI_Classic#36]
Officially request that an option be available to mana user classes that would allow the Azerite Crystal graphic to show for mana in place of the current blue-purplish orb.

**Comment by goldpaw** [comment]
Coming in the next update. :)

![Screenshot (219)](https://user-images.githubusercontent.com/6476535/75330525-872b2a80-5881-11ea-974a-d8d4ccfb542a.png)

![Screenshot (220)](https://user-images.githubusercontent.com/6476535/75330512-84c8d080-5881-11ea-9d68-3bdaddca4ac1.png)

**Comment by goldpaw** [comment]
Added and fixed and verified.
