### ISSUE TITLE
Both Azerite Crystal and Orb showing on top of each other/New text still visible after lvling

### ISSUE THREAD

**Issue by srtzero** [AzeriteTeam/AzeriteUI_Classic#37]
## The problem  
When changing zones, entering instances or anytime the UI has to reload Azerite is showing both the crystal and the orb. Also when hitting a new level the Minimap is still showing the NEW text instead of the asterisk mark.

### Make sure you can check all these boxes  
- [ X] I have the latest addon version available from CurseForge/Twitch.
- [ X] I restarted the entire game after updating the addon, not just relogged or reloaded. 

### Does this happen with NO other addons enabled?  

- [X ] Yes
- [ ] No

### What classes does it happen on?  

- [ ] Druid 
- [ ] Hunter 
- [X ] Mage 
- [ ] Paladin 
- [ ] Priest 
- [ ] Rogue 
- [X ] Shaman 
- [ ] Warlock 
- [ ] Warrior 

### Any logs, error output, etc?  
No error logs

### Steps to reproduce  
Was entering an instance which gave the loading screen. Also happens if I use the reload UI feature in Azerite. Was also in the instance when I leveled.

### Expected behaviour  

<img width="1920" alt="2020-02-29 (1)" src="https://user-images.githubusercontent.com/38842965/75609089-029d0e00-5b06-11ea-95ae-ac5370602632.png">
<img width="1920" alt="2020-02-29" src="https://user-images.githubusercontent.com/38842965/75609110-337d4300-5b06-11ea-8530-603ecc7117b1.png">

**Comment by goldpaw** [comment]
Fixed in 1.0.100-RC.
