### ISSUE TITLE
Movable Raidframes for healers

### ISSUE THREAD

**Issue by systenomi** [AzeriteTeam/AzeriteUI_Classic#38]
I'm always frustrated when I want to set up my ui but the raid frames are not centered 
***i would like to be able to move the Raidframes sideways**  in healer mode or have the option to disable it , so i dont have to use an additional addons for raidframes / have 2 raidframes at the same time taking unneccesary space.

**Describe alternatives you've considered**
just an option to disable Raidframes or get a skin for  one of the healing related raidframes to make them look like azerite ui.

**Comment by goldpaw** [comment]
They won't become movable, nothing in this UI will. But they can be disabled, though. Option for that has always been there! :) In the menu from the bottom right corner: 

![Screenshot (695)](https://user-images.githubusercontent.com/6476535/79642549-5fc84e00-819e-11ea-8105-fbf04e88191d.png)
