### ISSUE TITLE
LUA Error when summoning pet

### ISSUE THREAD

**Issue by xapher19** [AzeriteTeam/AzeriteUI_Classic#4]
## The problem  
When I summon my pet, I get an LUA Error.

### Make sure you can check all these boxes  
- [x ] I have the latest addon version available from CurseForge/Twitch.
- [x ] I restarted the entire game after updating the addon, not just relogged or reloaded. 

### Does this happen with NO other addons enabled?  

- [x ] Yes
- [ ] No

### What classes does it happen on?  

- [ ] Druid 
- [x ] Hunter 
- [ ] Mage 
- [ ] Paladin 
- [ ] Priest 
- [ ] Rogue 
- [ ] Shaman 
- [ ] Warlock 
- [ ] Warrior 

### Any logs, error output, etc?  

`Message: ...nterface\AddOns\AzeriteUI_Classic\front-end\root.lua:327: bad argument #3 to 'SetFormattedText' (string expected, got nil)
Time: Fri Aug 30 21:54:17 2019
Count: 6
Stack: ...nterface\AddOns\AzeriteUI_Classic\front-end\root.lua:327: bad argument #3 to 'SetFormattedText' (string expected, got nil)
[C]: in function `SetFormattedText'
...nterface\AddOns\AzeriteUI_Classic\front-end\root.lua:327: in function `Update'
...nterface\AddOns\AzeriteUI_Classic\front-end\root.lua:336: in function <...nterface\AddOns\AzeriteUI_Classic\front-end\root.lua:335>

Locals: (*temporary) = <unnamed> {
 0 = <userdata>
 msg = "Happiness: %s (%s) - DPS: %s"
 Update = <function> defined @Interface\AddOns\AzeriteUI_Classic\front-end\root.lua:300
 msgShort = "Happiness: %s - DPS: %s"
}
(*temporary) = "Happiness: %s (%s) - DPS: %s"
(*temporary) = "Happy"
(*temporary) = nil
(*temporary) = "125"
(*temporary) = "string expected, got nil"
`

**Comment by goldpaw** [comment]
Had a wrong variable name. Should be fixed in 1.0.32-RC.
