### ISSUE TITLE
Minimap issue

### ISSUE THREAD

**Issue by Fraytex** [AzeriteTeam/AzeriteUI_Classic#5]
## The problem  
Upon logging on to my character, the mini map is visible for a split second then fades to the xp information.  I can't switch back to minimap.

### Make sure you can check all these boxes  
- [x ] I have the latest addon version available from CurseForge/Twitch.
- [x ] I restarted the entire game after updating the addon, not just relogged or reloaded. 

### Does this happen with NO other addons enabled?  

- [x ] Yes
- [ ] No

### What classes does it happen on?  

- [ ] Druid 
- [ ] Hunter 
- [ ] Mage 
- [ ] Paladin 
- [ ] Priest 
- [ ] Rogue 
- [ ] Shaman 
- [ ] Warlock 
- [x ] Warrior

**Comment by goldpaw** [comment]
You have clicked the XP badge (circle with the XP percentage at the bottom of the map) and enabled sticky bars. Click it again to disable it. 

![Screenshot from 2019-09-01 11-42-17](https://user-images.githubusercontent.com/6476535/64074600-93a54080-ccad-11e9-9a05-e9d196958c31.png)
