### ISSUE TITLE
Action bar icons are way too dark

### ISSUE THREAD

**Issue by Twyzeas** [AzeriteTeam/AzeriteUI_Classic#7]
## The problem  

The action bar icons are too dark and rather hard to see. I don't see why they should be darker by default. I understand that you want to have hover states, but you can do that by darkening the frame only—same way as Bartender + Masque does with your theme.

### Make sure you can check all these boxes  
- [x] I have the latest addon version available from CurseForge/Twitch.
- [x] I restarted the entire game after updating the addon, not just relogged or reloaded. 

### Does this happen with NO other addons enabled?  

- [x] Yes
- [ ] No

### What classes does it happen on?  

- [ ] Druid 
- [ ] Hunter 
- [ ] Mage 
- [ ] Paladin 
- [ ] Priest 
- [x] Rogue 
- [ ] Shaman 
- [ ] Warlock 
- [ ] Warrior 

### Any logs, error output, etc?  

No.

### Steps to reproduce  

Start game.

### Expected behaviour  

Normal icon visibility, same as on default action bars.

### Actual behaviour  

Darkened, hard to see icons.

**Comment by goldpaw** [comment]
This is not a bug, it's intended. They are still quite easy to see. Darkening of unavailable abilities might make them hard to see, but that too is intended.

**Comment by Twyzeas** [comment]
Haven't found a place to leave general feedback, and since this is a serious issue with the accessibility, it should be fixed. I've read the forums looking for a solution and I'm clearly not the first asking for it. The addon's UX and UI is mostly great, please don't let these kind of small, but incredibly annoying 'features' ruin the experience.

—A fellow UX designer

**Comment by goldpaw** [comment]
Nothing too dark here. All available buttons are quite clear. 

![Screenshot from 2019-09-10 09-48-03](https://user-images.githubusercontent.com/6476535/64594455-55e0a000-d3b0-11e9-81c9-8233dc78eb2c.png)

**Comment by goldpaw** [comment]
If your monitor has a limited contrast range and the above picture isn't clear, I recommend lowering the contrast and increasing the brightness (or something similar) in the advanced graphic options of WoW, to solve that issue. 

![Screenshot from 2019-09-10 09-51-12](https://user-images.githubusercontent.com/6476535/64594558-8cb6b600-d3b0-11e9-82aa-8d53de770c81.png)

**Comment by Twyzeas** [comment]
When you have 24 icons shown, and you're in the heat of a battle, you definitely feel handicapped with the limited visibility. I have a calibrated, wide-gamut display with high dynamic range, so that shouldn't be the issue here.

Just from curiosity, why do you use a dark overlay on icons and the minimap? Your design is crisp, bold and beautiful—I really dig the art direction—yet there are a few things like this, that seem to have skipped user testing at all.

Anyways, thank you for your effort with the addon, I appreciate your hard work. I'm here only to provide some feedback.

**Comment by goldpaw** [comment]
Slightly brighter in 1.0.44-RC.
